---
apiVersion: v2
appVersion: 0.0.1
description: An helm chart for openldap
name: opendlap
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - openldap
home: https://github.com/mwinters-stuff/openldap-chart
sources:
  - https://github.com/mwinters-stuff/openldap-chart
  - https://github.com/osixia/docker-openldap
maintainers:
  - name: mwinters
    email: mathew@winters.nz
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
